name: Release tasks
on:
  release:
    types: [published]
jobs:
  upload-vendor-sources:
    env:
      VENDOR_TARBALL: mdevctl-${{ github.event.release.name }}-vendor.tar.gz
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Attach vendor source tarball
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: get vendor sources
        run: cargo vendor
      - name: package vendor sources
        run: tar -czvf ${VENDOR_TARBALL} vendor/
      - name: upload vendor source package
        run: gh release upload "${{ github.event.release.tag_name }}" "${VENDOR_TARBALL}"
  publish-crate:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: publish to crates.io
        uses: katyo/publish-crates@v2
        with:
          args: --no-verify
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
